import type { ThoughtSet } from '@/thoughts/content';

/**
 * What people worry about about 2300. Same rules as the other sets (PLAN.md
 * 7): first person, present tense, under sixty characters, gentle.
 *
 * The era shows in the nouns and nowhere else. The tower is tall, the light is
 * cool, the pod is late, and none of that has changed what anybody is actually
 * thinking about: the rent, the parent, the message that has not come back. A
 * few of these are word for word the ones from 1800 and 2020, which is the
 * whole point of the piece. The clothes change, the worries do not.
 *
 * Nothing here is a gadget for its own sake, and nobody explains their century
 * to themselves. People do not narrate the world they were born into.
 */
export const AFTER_THOUGHTS: ThoughtSet = {
  home: [
    'The window is dimmed again. I like the rain.',
    'I should call my mother.',
    'Sixty-one floors and I still hear the street.',
    'The rent is due on the first.',
    'One more year, then I rest.',
    'She still has not written back.',
    'The plants on the east side are doing better.',
    'I will start swimming tomorrow.',
    'My son has grown out of his shoes again.',
    'The plant wall needs pruning again.',
    'My daughter lives three towers over.',
    'The view from here never gets old.',
    'The kitchen garden gave us enough today.',
    'We moved up a level. It feels too high.',
    'The cat has found the warm floor again.',
  ],
  work: [
    'The report is due at four.',
    'Nobody read it. I know nobody read it.',
    'Three of us do the work of one, now.',
    'I do not understand half of what I approve.',
    'If I am careful, nobody notices me.',
    'He was promoted. I trained him.',
    'It will hold for another century. Probably.',
    'I have checked it twice. I will check it again.',
    'The flood model says we are safe. For now.',
    'I check the water gates twice a day.',
    'The tower is two hundred years old. It sways.',
    'I tend the roof gardens. Best job there is.',
    'The machines work. I watch them work.',
    'Nobody remembers why we do it this way.',
  ],
  market: [
    'Everything is cheaper on the lower level.',
    'She always keeps the best for herself.',
    'I came for one thing and forgot the thing.',
    'The tomatoes are better than they used to be.',
    'Nobody has time to cook it anyway.',
    'I will trade the hours, not the day.',
    'He gives good weight. I go back to him.',
    'Real tomatoes. Not the tower ones.',
    'Fish from the lower water, very fresh.',
    'I trade my herbs for her honey.',
    'The deck market smells of bread and rain.',
    'Everybody comes on the last day of the week.',
    'Old things from the lower city. I love them.',
  ],
  temple: [
    'Let her come back before the cold.',
    'My grandmother sat where I am sitting.',
    'It is quiet here, and I am grateful.',
    'I do not know if anyone is listening.',
    'Let the results be good. Just this once.',
    'I say their names. It costs me nothing.',
    'Thank you. Just thank you.',
    'The old shrine is under the water now.',
    'I light a lamp for the drowned city.',
    'I come for the quiet, mostly.',
    'The garden temple is full of birds.',
    'I pray for the water to stay down.',
    'My grandmother believed. I come for her.',
  ],
  park: [
    'The herons came back before we did.',
    'This was a road once. You can feel it.',
    'Sit a while. Nothing is waiting.',
    'The light is better here than up there.',
    'My father climbed that one as a boy.',
    'The bees are early this year.',
    'I have not been down here in months.',
    'This was all water, they say.',
    'The trees are older than the towers.',
    'Children climbing on the old wall.',
    'The fireflies came back this year.',
    'The bees are drowsy in the heat.',
    'I planted that tree. Look at it now.',
  ],
  street: [
    'The pod is late and I am not sorry.',
    'I know this turning without looking.',
    'Everyone is looking up except me.',
    'Rain by evening, I should think.',
    'That one was not here last spring.',
    'I will walk it. It is only twenty minutes.',
    'The lights come on before I am ready.',
    'The street is quieter than the pods.',
    'I walk the old road. It is still here.',
    'Moss between every paving stone.',
    'The heat comes up off the stones.',
    'That tower leans. I am sure it leans.',
    'Nobody walks down here. I like it.',
  ],

  byRole: {
    office: [
      'The system flagged it. I have to check.',
      'I oversee the machines. They do not need me.',
      'Fifty floors up and I still get vertigo.',
      'My shift is four hours. It feels like ten.',
      'I asked for the quiet desk by the plants.',
      'The report writes itself. I sign it.',
      'Everyone works from the gardens now.',
      'I miss when work was harder.',
      'The lift to level sixty is slow today.',
      'I am good at something nobody needs.',
    ],
    shop: [
      'People still want things made by hand.',
      'I grow the herbs on the roof myself.',
      'The deck stall is busy on market day.',
      'Nobody needs what I sell. They want it.',
      'I repair old things. There is always work.',
      'Visitors come to see the old way.',
      'Real bread. People queue for real bread.',
      'I barter more than I sell now.',
      'The garden gives me more than I can sell.',
      'My grandmother would laugh at my prices.',
    ],
    student: [
      'I can learn anything. I cannot choose.',
      'My tutor never sleeps. It is not a person.',
      'Everyone else knows what they want.',
      'I want to study the old flood records.',
      'I want to work with my hands. They worry.',
      'The history of the towers is so dull.',
      'I would rather be down by the water.',
      'She is in the botany course too.',
      'I read about cities that had cars.',
      'I will go and see the old wall one day.',
    ],
    retired: [
      'I remember when the water came up.',
      'My great-grandson plants my old seeds.',
      'I have lived a hundred and twelve years.',
      'The towers were new when I was young.',
      'They fixed my knees. Not my memory.',
      'I tell them about the rains. They listen.',
      'Nobody needs to work now. I miss it.',
      'I walk the lower level every morning.',
      'The herons came back in my lifetime.',
      'I have buried two husbands. Enough.',
    ],
    night: [
      'The towers hum all night. I tend them.',
      'Night maintenance. Just me and the lights.',
      'The gardens are lit blue at night.',
      'I watch the water line. It is steady.',
      'The pods run empty after midnight.',
      'I like the city best when it is asleep.',
      'The machines do not need me. I come anyway.',
      'Up here the stars are sharp.',
      'My shift ends when the first pod runs.',
      'The river is loud at night. Good.',
    ],
  },

  byTime: {
    dawn: [
      'The windows brighten on their own.',
      'The herons are fishing on the lower deck.',
      'Mist on the gardens. Nobody up but me.',
      'The first pod glides past the window.',
      'Birdsong from the plant wall. Every day.',
      'I watch the sun come up over the water.',
      'The air smells of wet leaves.',
      'The towers catch the light first.',
    ],
    morning: [
      'The pods are full going down.',
      'The garden deck is busy already.',
      'The heat lifts off the glass by nine.',
      'I take the stairs. It is good for me.',
      'The market on level twelve opens now.',
      'The children are in the learning garden.',
      'Everything is so clean in the morning.',
      'Water the tomatoes before the heat.',
    ],
    afternoon: [
      'The towers shade the whole street now.',
      'Rain on the glass. The gardens drink.',
      'Too warm for the upper decks.',
      'The pods are quiet this time of day.',
      'Everyone is resting in the cool levels.',
      'The plant wall is buzzing with bees.',
      'I nap in the green room. Everyone does.',
      'The light through the glass is lovely.',
    ],
    evening: [
      'The towers light up one by one.',
      'Supper on the roof garden tonight.',
      'The pods are full going home.',
      'The water is gold in this light.',
      'The herons fly back over the towers.',
      'Music from the deck below.',
      'I sit by the window and watch the city.',
      'The windows dim themselves for the night.',
    ],
    night: [
      'The towers glow. The city breathes.',
      'The windows dimmed. I did not ask.',
      'I cannot sleep. The city never does.',
      'The river sounds louder in the dark.',
      'Someone on the next tower is awake too.',
      'The gardens smell sweeter at night.',
      'I dreamed of the old flood again.',
      'The last pod has gone. So quiet.',
    ],
  },
};
