import type { ThoughtSet } from '@/thoughts/content';

/**
 * What people worry about in the citadel, about 1800. Same rules as the modern
 * set (PLAN.md 7): first person, present tense, under sixty characters, gentle.
 *
 * The era shows in the nouns and nowhere else: the mandarin's exam, the price
 * of silk, the drum at dawn, the gate that closes at dusk. A clerk worries
 * about his report the way an office worker does, because that is the whole
 * point of the thing.
 */
export const CITADEL_THOUGHTS: ThoughtSet = {
  home: [
    'The roof leaks again when it rains.',
    'My son studies by the lamp until late.',
    'I should visit my mother in the village.',
    'The rice will last until the harvest.',
    'He is too young to marry. She says no.',
    'I will mend the net tonight.',
    'The drum wakes me before I am ready.',
    'One good year. That is all I ask.',
    "The ancestors' tablets need dusting.",
    'We will eat the good rice at Tết.',
    'Her mother wants a proper match for her.',
    'The mat is worn through where I kneel.',
    'My daughter is weaving, and singing.',
    'The well is low. Carry water from the river.',
  ],
  work: [
    'The mandarin will read it or he will not.',
    'I have copied this page four times.',
    'My brush is worn down to nothing.',
    'The exam is in the spring.',
    'He passed and I did not.',
    'If I am careful, nobody notices me.',
    'The ledger does not balance. It will.',
    'I know the characters. At the desk I forget.',
    'Twenty years of this and my back is bent.',
    'The dye will not take. Again.',
    'The master says my joints are crooked.',
    'The palace wants a hundred by the festival.',
    'Lacquer takes nine coats. This is the fourth.',
    'I hammer and I think of nothing.',
    'The foreman takes a cut of everything.',
  ],
  market: [
    'Silk is dearer than it was last month.',
    'She weighs it light. I say nothing.',
    'Salt, thread, and something sweet.',
    'The fish is not fresh. I will look again.',
    'My daughter wants the blue cloth.',
    'I came for rice and I am still here.',
    'The boats came in late today.',
    'Two coins less and it is a good day.',
    'Her tea is better than the others.',
    'Betel for my mother. She insists.',
    'Lotus seeds, sticky rice, and sugar.',
    'The cloth seller from the north is back.',
    'That duck is too thin. Next one.',
    'The ferry fee went up. So did everything.',
    'Candied ginger for the children.',
  ],
  temple: [
    'Let my son pass the exam.',
    'I am not asking for much.',
    'The incense smells like my childhood.',
    'Let the rain come in time.',
    'My grandmother knelt on this stone.',
    'Thank you. Just thank you.',
    'I will try to be kinder.',
    'Let him come home from the river.',
    'Let the rains come, but not the flood.',
    'I burn incense for the ones I lost.',
    'Let my husband come home from the war.',
    'A good harvest and I will return.',
    'The monk smiled at me. I feel better.',
    'Let the fever leave the little one.',
  ],
  park: [
    'The willows are heavy this year.',
    'Cooler here than in the lane.',
    'The old man feeds the birds again.',
    'Five more breaths, then I go.',
    'My knees are not what they were.',
    'It is quiet inside the wall.',
    'Nothing is wrong. That is strange.',
    'The lotus pond is in flower. I had to see.',
    'The old men are playing chess again.',
    'A kite is caught in the banyan.',
    'The shade of this tree is my favourite.',
    'The heron is so still. I hold my breath.',
    'Children fishing with a string and a stick.',
  ],
  street: [
    'The drum sounded. I am late.',
    'The gate closes at dusk.',
    'This cart is heavier than it was.',
    'It will rain before I reach the bridge.',
    'I should have taken the other lane.',
    'The ox is slow today. So am I.',
    'My sandals are worn through.',
    'Just get to the market and back.',
    'One day I will walk this road for pleasure.',
    'Make way for the palanquin.',
    'The mud is up to my ankles in this lane.',
    'The water seller is late. I am thirsty.',
    'A procession to the palace. Stand back.',
    'This lane smells of fish sauce and smoke.',
    'The bridge is packed. I will wait.',
  ],

  byRole: {
    office: [
      'The magistrate wants it copied by dusk.',
      'One blot and I start the page again.',
      'The ink is thin. The paper is dear.',
      'He can barely read. He signs everything.',
      'Twelve years a clerk. Twelve more, perhaps.',
      'The seal must be straight. It never is.',
      'I copy the law. I do not understand it.',
      'The tax rolls are wrong. I will fix them.',
      'If I pass the exam, no more copying.',
      'My wrist aches from the brush.',
    ],
    shop: [
      'The silk from the north is late again.',
      'Three coins for that? I laughed.',
      "The mandarin's cook buys from me now.",
      'Rain means the boats do not come.',
      'The market fee is due by the new moon.',
      'My scales are honest. Not all are.',
      'The fish must go today or not at all.',
      'The court is buying. Prices will rise.',
      'I sold the last lantern before noon.',
      'Tomorrow the barge brings salt.',
    ],
    student: [
      'Four thousand characters. I know three.',
      'The provincial exam is in the autumn.',
      'My father failed it twice. I must not.',
      'I read by the lamp until the oil runs out.',
      'The classics again. Always the classics.',
      'The teacher struck my hand. I deserved it.',
      'If I pass, my whole village will know.',
      'I would rather be out on the river.',
      'Her family would not have a failed scholar.',
      'I recited it perfectly. To myself.',
    ],
    retired: [
      'I served the old king. Nobody remembers.',
      'My sons are in the capital. They rarely write.',
      'I have seen three floods and two famines.',
      "The ancestors' altar needs new incense.",
      'My eyes are too weak for the brush now.',
      'I tend the little garden. It tends me.',
      'The young do not bow the way we did.',
      'I remember the town before the new wall.',
      'Let my grandson pass. Then I can go.',
      'I sit by the gate and watch the day.',
    ],
    night: [
      'Strike the drum, walk the wall, again.',
      'The river is best fished in the dark.',
      'The lantern keeps going out in the wind.',
      'Nothing moves but the river and me.',
      'The gate is barred. I am on the right side.',
      'I call the watches. Nobody listens.',
      'Fog on the river. I cannot see the bank.',
      'My wife is asleep. My nets are wet.',
      'The palace lamps burn all night.',
      'Dawn comes, and then I can sleep.',
    ],
  },

  byTime: {
    dawn: [
      'The drum. My feet find the cold floor.',
      'Mist on the river. My father is out there.',
      'The monks are chanting. I love that sound.',
      'Light the fire before the others wake.',
      'The gate opens. The carts come in.',
      'I have rice to cook and water to carry.',
      'The cockerel again. I hate that bird.',
      'Cold water on my face. Awake now.',
    ],
    morning: [
      'The market is full by the second drum.',
      'The mandarin rides past. Head down.',
      'The heat is coming. Work while you can.',
      'Carry this, carry that, carry the rest.',
      'The boats from upriver are in. My brother?',
      'The schoolboys recite. I still know it.',
      'Tea, then work. That is the order.',
      'Water the garden before the sun is high.',
    ],
    afternoon: [
      'Too hot. I will sit under the eaves.',
      'The rain will come. It always comes now.',
      'Rest after the meal. Just a little.',
      'The cicadas are so loud I cannot think.',
      'The ink dries too fast in this heat.',
      'Nothing moves in the lanes but dogs.',
      'Fan yourself and wait for the breeze.',
      'The river is low. The boats are slow.',
    ],
    evening: [
      'The evening drum. Home before the gate.',
      'Smoke from every kitchen in the lane.',
      'Lanterns on the river. So many lanterns.',
      'The children are chasing fireflies. I did too.',
      'Rice and fish, and the day is done.',
      'The temple bell. Time to light incense.',
      'The gate shuts soon. Walk faster.',
      'The swallows are going home. So am I.',
    ],
    night: [
      'The watchman calls the second watch.',
      'The oil is low. Read one more page.',
      'The frogs after the rain. I cannot sleep.',
      'A dog barking across the river.',
      'Is the ox tied properly? I think so.',
      'The mosquitoes found me again.',
      'The palace is lit. What do they do all night?',
      'Sleep, before the drum comes again.',
    ],
  },
};
