import type { ThoughtSet } from '@/thoughts/content';

/**
 * The shared human core: what anybody might think, in any age.
 *
 * Every era draws on this list underneath its own. That makes the piece's
 * idea structural instead of a handful of lines copied between files: a
 * clerk in 1800, a clerk in 2020 and a clerk in 2300 are picking from exactly
 * the same worries, dressed in different nouns (thoughts/content.ts,
 * `thoughtPool`).
 *
 * So every line here has to be true in all four worlds. No phones, no
 * clocks, no coffee, no money with a name on it, no machines. What is left is
 * what was always there: the rent, the child, the knee, the one who has not
 * written back, the light at the end of the day.
 *
 * Same rules as every set (PLAN.md 7): first person, present tense, under
 * sixty characters, gentle. About one in ten light, about one in ten tender.
 */
export const HUMAN_THOUGHTS: ThoughtSet = {
  home: [
    'Did I shut the door properly?',
    'The house is too quiet without her.',
    'I should fix that before it gets worse.',
    'Everyone is asleep. Finally, some quiet.',
    'I burnt it again. Nobody will notice.',
    'The children are fighting. Let them.',
    'I keep meaning to write to my brother.',
    'This bed has never felt so good.',
    'I will clean tomorrow. I mean it.',
    'She laughed at my joke. A real laugh.',
    'The roof sounds louder when it rains.',
    'I cooked too much again.',
    'We have not argued in a week. Good.',
    'My feet hurt. Everything hurts a little.',
    'I found his old shirt today.',
    'The little one said my name today.',
    'Somebody has eaten the last of it.',
    'I can hear the neighbours again.',
    'This is the best part of the day.',
    'I am tired in a way sleep does not fix.',
    'I will say sorry in the morning.',
    'I love this house, even the draught.',
    'Where did I put it? It was just here.',
    'Our first home was smaller than this.',
  ],
  work: [
    'Nobody notices when it goes right.',
    'I could do this with my eyes shut.',
    'He is watching me again.',
    'Only three more hours. Two and a half.',
    'I made a mistake. Nobody saw. Yet.',
    'She is kind to me. I do not know why.',
    'I am paid for eight hours and give ten.',
    'I used to love this work.',
    'If I stop now I will never start again.',
    'Keep your head down and it passes.',
    'That was good work. I will remember it.',
    'My hands know this better than I do.',
    'Tomorrow will be the same. That is fine.',
    'I am hungry and it is not even noon.',
    'Is it too late to learn something else?',
    'He shouted, and then he said thank you.',
    'I should ask for more. I will not.',
    'Somebody has to do it. It is always me.',
  ],
  market: [
    'Everything costs more than I remember.',
    'She always gives me a little extra.',
    'I will know it when I see it.',
    'Do not buy what you do not need.',
    'I came for salt. I have everything but.',
    'The smell of this place. I love it.',
    'He is cheating me and he knows I know.',
    'Enough for three days if we are careful.',
    'I should not have bought that.',
    'The best ones go early. I am late.',
    'I will haggle. I never haggle.',
    'My mother would have known the price.',
    'Too many people. I will come back.',
    'Something sweet for the children.',
    'The same stall, twenty years now.',
    'Is it ripe? I can never tell.',
  ],
  temple: [
    'Please let him be well.',
    'I came to ask, and I forgot what.',
    'I am not sure I believe. I come anyway.',
    'Forgive me. I know what I did.',
    'Keep them safe. That is all.',
    'It smells the way it did when I was small.',
    'I do not pray. I just sit.',
    'One more year with her. Please.',
    'Let this year be kinder than the last.',
    'I light one for my father every year.',
    'Everyone here is asking for something.',
    'The quiet is the only answer I need.',
    'Help me be patient with him.',
    'I promised to come. So I came.',
    'I am grateful and I forget to say it.',
    'I asked for courage. Still waiting.',
  ],
  park: [
    'Look at that tree. Just look at it.',
    'The wind smells like rain.',
    'I could sit here all day.',
    'Those two are in love. Good for them.',
    'The children never get tired.',
    'When did I last do nothing?',
    'My knees say go home. I say not yet.',
    'I used to run here. Now I walk.',
    'A bird landed right next to me.',
    'A little longer, then I go back.',
    'Nobody here needs anything from me.',
    'I should bring her here some day.',
    'The grass is cold. I do not mind.',
    'That dog is happier than any of us.',
    'I forgot how big the sky is.',
    'I came to think and did not think at all.',
    'This bench has seen a lot, I bet.',
    'The leaves are turning already.',
  ],
  street: [
    'Left or right? I always forget.',
    'That face. Where do I know that face from?',
    'I should have worn the other shoes.',
    'Home is still a long way off.',
    'Everyone seems to know where they are going.',
    'I will take the long way. I have time.',
    'Did I say the wrong thing back there?',
    'Smells like somebody is cooking onions.',
    'I keep thinking about what she said.',
    'The same walk, every day, for years.',
    'I would like to be somewhere else.',
    'It is going to rain. I can feel it.',
    'I passed my old school. Still standing.',
    'Nobody is looking at me. Good.',
    'I will buy something on the way back.',
    'My bag is heavier than it should be.',
    'He waved. I waved. Who was that?',
    'I should have said yes.',
    'Keep walking. Do not think about it.',
    'I know every stone of this road.',
    'Why is everyone so slow today?',
    'I will be early for once. Watch me.',
  ],

  byRole: {
    office: [
      'I am good at a job I never chose.',
      'He called me in. My stomach dropped.',
      'The work is fine. The people are the work.',
      'I have not had a real rest in years.',
      'I could run this place better than him.',
      'They will never know how hard that was.',
      'I am saving up. For what, I do not know.',
      'I wanted to be something else once.',
      'Payday cannot come soon enough.',
      'I will leave. Next year. Probably.',
      'Please let him be in a good mood.',
      'I finished early and pretended I had not.',
      'She trusts me with it. I will not fail her.',
      'Sitting all day is ruining my back.',
    ],
    shop: [
      'Smile. They are always right.',
      'Nobody has bought anything all morning.',
      'The same questions, a hundred times.',
      'My feet have been standing since dawn.',
      'That one always pays, always smiles.',
      'I will not drop the price. I will not.',
      'My mother ran this stall before me.',
      'Business is slow. The rent is not.',
      'Look busy. Look like you are selling.',
      'I know every face on this street.',
      'Please, just one good day this week.',
      'I gave her too much change. Oh well.',
      'Tired of selling. Never tired of people.',
      "One day this will be my daughter's.",
    ],
    student: [
      'I do not know what I want to be.',
      'Everyone is cleverer than me here.',
      'I studied the wrong chapter. Of course.',
      'If I fail, they will be so disappointed.',
      'She sat next to me. She sat next to me.',
      'I will learn it properly next time.',
      'I am old enough to decide. Nobody agrees.',
      'My teacher said I had talent. Once.',
      'I want to go somewhere far away.',
      'Why do I remember songs but not this?',
      'My friends all seem to have it worked out.',
      'One day I will look back and laugh.',
      'I am hungry all the time.',
      'I wish I could just ask her.',
      'Everything is so important and so dull.',
      'I am going to be somebody. I think.',
    ],
    retired: [
      'The young walk so fast now.',
      'My grandson is taller than me. When?',
      'I remember this street before the houses.',
      'I have more time than I know what to do with.',
      'Everyone I grew up with is gone or going.',
      'My knees know the weather before I do.',
      'I should write it all down before I forget.',
      'She has been gone ten years. Still.',
      'Nobody asks my advice. I give it anyway.',
      'I nap now. I used to laugh at that.',
      'I would do it all again. Most of it.',
      'The little ones make it all worth it.',
      'I have outlived my own worries.',
      'Every day is a gift. Some are strange gifts.',
      'I told that story again. They were kind.',
      'I worked my whole life for this bench.',
    ],
    night: [
      'The whole town is asleep but me.',
      'I sleep when the birds wake up.',
      'Night work makes you a ghost.',
      'I have not seen the sun in days.',
      'Stay awake. Just a few more hours.',
      'The quiet out here is almost nice.',
      'Everyone I love is asleep right now.',
      'I hear things at night nobody else hears.',
      'I will sleep all day and still be tired.',
      'The stars are out. I forget to look up.',
      'My body does not know what time it is.',
      'Someone has to keep watch.',
      'The dark is not so bad once you know it.',
      'I miss eating supper with them.',
    ],
  },

  byTime: {
    dawn: [
      'Not yet. Just a little longer.',
      'The first light is the best light.',
      'I am up before the birds again.',
      'The day has not gone wrong yet.',
      'Cold floor, warm bed. Hard choice.',
      'I dreamed about my mother.',
      'Everything is grey and soft and quiet.',
      'Today I will be patient. Today.',
      'My back is stiff. It will loosen.',
      'Who is that, out so early?',
      'The street is empty. I like it like this.',
      'Another day. Let it be a good one.',
    ],
    morning: [
      'Already behind, and the day has barely begun.',
      'So much to do. Start with one thing.',
      'The sun is warm on my back.',
      'I forgot to eat. I will eat later.',
      'Everyone is in a hurry this morning.',
      'I feel good today. For no reason at all.',
      'Busy morning. Good. Time goes faster.',
      'I should have left earlier.',
      'The air is fresh before the heat comes.',
      'Something hot to drink would fix this.',
      'I said good morning and meant it.',
      'Half the day is still ahead of me.',
    ],
    afternoon: [
      'The heat makes everything slow.',
      'I could sleep right here, right now.',
      'After lunch nobody is any use.',
      'This is the long part of the day.',
      'How is it only the afternoon?',
      'The shadows are getting longer.',
      'I ate too much. I regret nothing.',
      'A little rest, then back to it.',
      'Everything smells of dust and cooking.',
      'I should be doing something. I am not.',
      'The hottest hour. Stay in the shade.',
      'Nearly done. Nearly.',
    ],
    evening: [
      'Done for today. Done.',
      'The light goes gold before it goes.',
      'I can smell supper from here.',
      'Everyone is heading home.',
      'I made it through another one.',
      'The best hour. Everything slows down.',
      'I will call on her once I sit down.',
      'The lamps are coming on.',
      'I never saw the day go.',
      'Tonight I will not think about work.',
      'I am so tired and so glad.',
      'The sky is pink over the roofs.',
      'Someone is singing somewhere.',
      'Home soon. Nearly home.',
    ],
    night: [
      'Why am I thinking about this now?',
      'I cannot sleep. I never can.',
      'Tomorrow will be better. It has to be.',
      'Everyone is asleep. It is only me.',
      'I said the wrong thing, years ago.',
      'The house makes noises at night.',
      'Did I bar the door? I will check.',
      'I miss someone I have not seen in years.',
      'Listen. You can hear the whole town breathe.',
      'I am lucky. I forget that in the day.',
      'One more thing to worry about. Sleep.',
      'The moon is so bright tonight.',
      'I should not have eaten so late.',
      'Tomorrow I will say it to her face.',
      'Everything feels bigger in the dark.',
      'Close your eyes. Just close them.',
    ],
  },
};
