import type { ThoughtSet } from '@/thoughts/content';

/**
 * What people worry about in Wyrmrest. Same rules as every other set (PLAN.md
 * 7): first person, present tense, under sixty characters, gentle.
 *
 * The magic is in the nouns and nowhere else. There is a wyrm asleep under the
 * hill and there are things in the wood, and none of that has changed what
 * anybody is actually thinking about: the rent, the child, the knee that hurts
 * in the cold, whether he meant what he said. Several of these are word for
 * word the ones from 1800 and 2020, which is the whole point of the piece.
 *
 * Nobody here is awed by their own world. You are not amazed by the weather
 * you grew up in, and a monster you have lived beside all your life is a
 * nuisance, a danger and a piece of local news, in that order. So: nobody
 * narrates the magic, nobody explains the rules of it, and nobody says
 * anything a person would not say about a wolf.
 */
export const MYTH_THOUGHTS: ThoughtSet = {
  home: [
    'The fire is going out and I am not moving.',
    'I should call on my mother.',
    'The roof leaks over the bed, of course.',
    'Rent is due at the quarter day.',
    'One more winter, then I rest.',
    'She still has not sent word.',
    'The beans came up better on the north side.',
    'The little one is frightened of the hill again.',
    'He has grown out of his boots. Again.',
    'Salt the rest of it before it turns.',
    'Bar the shutters. The wind is up.',
    'The hearth smokes when it rains.',
    'My son wants to go into the wood.',
    'We need wood for the winter. Lots.',
    'The goat got into the garden again.',
    'My husband went out with the heroes.',
  ],
  work: [
    'It has to be finished before the gate shuts.',
    'Nobody checked it. I know nobody checked it.',
    'Three of us do the work of one.',
    'I do not understand half of what I am told.',
    'If I keep my head down, nobody notices me.',
    'He got the contract. I taught him the trade.',
    'It will hold. It has held for eighty years.',
    'I have counted it twice. I will count it again.',
    'My hands are worse in this cold.',
    'The bellows have a hole. I will patch it.',
    'I have three horses to shoe before noon.',
    'The thatch needs doing before winter.',
    'The lord wants the tower repaired.',
    'Leather, needle, thread. Again.',
    'The mill is slow. Check the race.',
  ],
  market: [
    'Everything is dearer since the road closed.',
    'She keeps the good ones under the counter.',
    'I came for one thing and forgot the thing.',
    'The eggs are better than they were.',
    'Nobody has time to cook it anyway.',
    'He gives honest weight. I go back to him.',
    'Trade for it. Do not pay coin for it.',
    'That is the third cart through today.',
    'Wool is cheap this year. I will buy now.',
    'The carters are late from the coast.',
    'Honey from the wood. Very dear.',
    'Pies. Hot pies. I cannot resist.',
    'She sells charms against the wood.',
    'A goose for the feast. A fat one.',
  ],
  temple: [
    'Let her come home before the cold.',
    'My grandmother knelt where I am kneeling.',
    'It is quiet here, and I am grateful.',
    'I do not know if anyone is listening.',
    'Let it go well. Just this once.',
    'I say their names. It costs me nothing.',
    'Thank you. Just thank you.',
    'Keep him off the hill. That is all I ask.',
    'Keep him safe in the wood.',
    'Let the harvest last the winter.',
    'I light a candle for the ones who went out.',
    'The priest says the hill is holy.',
    'Let the watch keep awake tonight.',
    'Old stones, old prayers. Still here.',
  ],
  park: [
    'The birds came back before we did.',
    'Sit a while. Nothing is waiting.',
    'The light is better on this side.',
    'My father climbed that one as a boy.',
    'The bees are early this year.',
    'I have not been down here in months.',
    'You can hear it breathing if you stay still.',
    'The oak is older than the keep.',
    'Children playing heroes and beasts. So did I.',
    'The brook is high after the rain.',
    'Blackberries by the wall. Nobody knows.',
    'The swans are back on the pond.',
    'I lie in the grass and watch the clouds.',
  ],
  street: [
    'The gate shuts at dusk and I am slow.',
    'I know this turning without looking.',
    'Everyone is looking up except me.',
    'Rain by evening, I should think.',
    'That was not here last spring.',
    'They came back three short. Nobody is saying.',
    'Do not look at it. Just keep walking.',
    'The bell went early. That is never good.',
    'It is only twenty minutes on foot.',
    'Mind the cart. Mind the mud.',
    'The smith is shouting at his boy again.',
    'A hero walked past. Taller than I thought.',
    'Pigs loose in the lane. Not my pigs.',
    'The bell rang twice. What does that mean?',
    'The wall is always cold in the shade.',
  ],

  byRole: {
    office: [
      'The guild master wants it by the fair.',
      'The forge is too hot. My arms are gone.',
      'Three swords by the new moon. Impossible.',
      'The lord pays late and pays short.',
      'I patched the wall again. It will fall again.',
      'My apprentice burnt the good leather.',
      'Guard the gate. Watch the road. Again.',
      'The mill wheel is stuck. Wet feet again.',
      'I built half this street. Nobody knows.',
      'A hero wants his blade by tonight.',
    ],
    shop: [
      'The wood road is closed. No timber.',
      'Heroes buy rope and bread. Always rope.',
      'The tithe man comes on market day.',
      'Nobody buys candles in summer.',
      'My cheese is the best in three villages.',
      'Salt from the coast. Worth its weight.',
      'The carters say the pass is dangerous.',
      'I will not sell to that one again.',
      'The fair is next week. Bake everything.',
      'Beast hide sells well. I do not ask.',
    ],
    student: [
      'The master says I will never be a smith.',
      'I want to go with the heroes. Mother says no.',
      'I swept the forge for a year. Still sweeping.',
      'The scribe says I have a good hand.',
      'I can read now. I read everything.',
      'One day I will make something that lasts.',
      'I burnt my hand again. It is fine.',
      'The old smith knew my grandfather.',
      'I will be a guildsman. Then they will see.',
      'I want to see what is beyond the hills.',
    ],
    retired: [
      'I saw the hill move once. Nobody believes me.',
      'My sword is on the wall. It stays there.',
      'I have buried too many friends from the wood.',
      'The wall was half this size when I was a boy.',
      'My grandson wants to be a hero. I said no.',
      'I remember the winter the well froze.',
      'Nobody tells the stories right any more.',
      'I have outlived three lords.',
      'My hands shake. They did not use to.',
      'I sit by the fire and remember the road.',
    ],
    night: [
      'I change the watch at the bell.',
      'Something moved at the edge of the wood.',
      'Torches on the wall. Eyes on the dark.',
      'The hill breathes at night. I swear it.',
      'Nobody comes to the gate after dark. Good.',
      'My hands are numb up here on the wall.',
      'I count the stars. I lose count.',
      'The beasts are loud. I will not sleep.',
      'Keep the fire going. Keep your eyes open.',
      'Dawn, then bed. Dawn, then bed.',
    ],
  },

  byTime: {
    dawn: [
      'I am first through the gate again.',
      'The cockerel, the bell, and then me.',
      'Frost on the wall. I need a thicker cloak.',
      'The smith is hammering. My head hurts.',
      'Mist over the hill. It looks like breath.',
      'The heroes are off early. I wish I could go.',
      'I draw the water before the queue.',
      'The ovens are lit. My stomach knows.',
    ],
    morning: [
      'The square is filling up. I am late.',
      'Carts from the villages. Mud on my boots.',
      'The lord rides out. I keep my head down.',
      'The mill is turning. Good sign.',
      'The bell for the morning service.',
      'The fields need turning before the rain.',
      'Someone is shouting in the square again.',
      'The heroes went out by the east gate.',
    ],
    afternoon: [
      'Too warm for honest work. I will rest.',
      'The tavern is full. I will squeeze in.',
      'The shadow of the keep across the square.',
      'A cart has lost a wheel in the lane.',
      'A nap under the oak. Nobody will know.',
      'The heroes are back. One is limping.',
      'Flies everywhere. Summer, then.',
      'The bread is gone. Bake more tomorrow.',
    ],
    evening: [
      'The gate shuts at dusk. Hurry.',
      'Lanterns in every window. Mine too.',
      'Stew again. I do not mind.',
      'The tavern is singing the old songs.',
      'The heroes are telling their stories.',
      'Bolt the shutters before dark.',
      'The bell rings. I hurry in with the rest.',
      'The hill is gold in the last light.',
    ],
    night: [
      'Something is howling in the wood.',
      'The candle is nearly out. One more page.',
      'The watch is on the wall. I can sleep.',
      'The hill has not moved. Good.',
      'The fire is low. I will not get up.',
      'Wolves, or worse. Do not think about it.',
      'I have never seen the stars so clear.',
      'I dreamed the hill was breathing.',
    ],
  },
};
